# Usar uma imagem base do Python
FROM python:3.9

# Criar diretório de trabalho dentro do container
WORKDIR /app

# Copiar arquivos para dentro do container
COPY model_script.py requirements.txt /app/

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Criar diretório para armazenar modelos
RUN mkdir -p /app/models
RUN mkdir -p /app/logs

# Comando de execução do script
CMD ["python", "/app/model_script.py"]
