version: '3.8'

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile-model
    volumes:
      - ./model/models:/app/models
      - ./model/logs:/app/logs
    container_name: model_container
    restart: "no"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-webapp
    volumes:
      - ./model/models:/app/models  # A API acessa os modelos treinados
    ports:
      - "5001:5001"
    depends_on:
      - model
    container_name: webapp_container
    restart: always
