

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile-Jenkins
    container_name: jenkins_container
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permitir que o Jenkins controle Docker
      - jenkins_home:/var/jenkins_home
      # Removido: - .:/var/jenkins_home/workspace/mlops_v1  # Montagem removida para evitar problemas de permissão

  model:
    build:
      context: ./model
      dockerfile: Dockerfile-model
    volumes:
      - ./model/models:/app/models
      - ./model/logs:/app/logs
    container_name: model_container
    restart: "no"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-webapp
    volumes:
      - ./model/models:/app/models  # A API acessa os modelos treinados
    ports:
      - "5001:5001"
    depends_on:
      - model
    container_name: webapp_container
    restart: always

volumes:
  jenkins_home:
