version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile-Jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
      - mlflow_db:/mlflow/db

  model:
    build:
      context: ./model
      dockerfile: Dockerfile-model
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./model/models:/app/models
      - ./model/logs:/app/logs
    container_name: model_container
    restart: "no"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-webapp
    volumes:
      - ./model/models:/app/models
      - ./model/logs:/app/logs
    ports:
      - "5001:5001"
    depends_on:
      - model
    container_name: webapp_container
    restart: always

volumes:
  jenkins_home:
  mlflow_artifacts:
  mlflow_db:
