FROM jenkins/jenkins:lts

# Instalar plugins necessários
RUN jenkins-plugin-cli --plugins git pipeline-stage-view blueocean

# Instalar Docker e Docker Compose
USER root
# ===> Align Docker group with host (replace 999 with your host GID)
RUN groupadd -g 989 docker \
    && usermod -aG docker jenkins \
    && apt-get update \
    && apt-get install -y docker.io docker-compose \
    && rm -rf /var/lib/apt/lists/*

USER jenkins

# Copiar arquivos de configuração
COPY casc.yaml /var/jenkins_home/casc.yaml
COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

# Configurar o Jenkins para usar o Configuration as Code
ENV CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
