# Usar Python como base
FROM python:3.9

# Create the directory for MLflow artifacts
RUN mkdir -p /mlflow/artifacts

# Criar diretório de trabalho dentro do container
WORKDIR /app

# Copiar arquivos
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código da API e frontend
COPY . /app/

# Expor a porta da API
EXPOSE 5001

# Comando para rodar a API
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]
